server:
  port: 8088

spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: SERVICE-CLIENT

  application:
    name: SERVICE-CLIENT

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/Micro_ClientDB?createDatabaseIfNotExist=true
    username: root
    password: root
